name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: tomshr29
          password: ${{ secrets.TOKEN_TOK }}

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/tomshr29/t29:latest .

      - name: Push the Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/tomshr29/t29:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker run -d \
              --name my_container \
              -p 3333:3333 \
              ghcr.io/tomshr29/t29:latest
